### ISSUE TITLE
Mobile app support

### ISSUE THREAD

**Issue by manhtai** [rvilarl/pianoplay#5]
Firstly, thanks for making a beautiful free app!

However it's not easy for me to plug the keyboard into a desktop computer while playing. I assume this would be the case for most users.

Do you have any intentions to make this a mobile app? And iPad app would be very nice.

Cheers!

**Comment by rvilarl** [comment]
Hi! Thanks for your feedback, I hope you enjoy it.

I am not planing to do any mobile app. I do not plan to join Apple Development program.

The only thing missing in apple in the webmidi support on their browsers. There is a project in github providing this support but it is outdated. I did set an issue but I got no reaction:

https://github.com/mizuhiki/WebMIDIAPIShimForiOS/issues/8

**Comment by manhtai** [comment]
I see, thanks for the info.

In the meantime, I dig around your source code and see it's written using Ionic so I think ionic-native would be a quick option here to packge your app into a mobile app. Let me see what I can do here.

Keep up the good work!

**Comment by rvilarl** [comment]
Let me know if you make progress! If you are in the developer program from Apple it would be great that you fixed the webmidiapp mentioned above.
