### ISSUE TITLE
Request For Contact Information

### ISSUE THREAD

**Issue by loganknecht** [rvilarl/pianoplay#6]
Hello @rvilarl and @Smibu 

This is such a lovely and wonderful solution!

I have a free website called Piano Gym that uses a continuous based approach for cursor management.

See https://PianoGym.com or this YouTube video for clarity.
https://www.youtube.com/watch?v=faxNDhOjlh4

I don't feel like I've nailed the cursor and playing input management down correctly, which leads to it feeling less than satisfactory when playing. I have been looking for others to collaborate with to get to a satisfying solution for this and it seems as though you are both on track to get to that solution!

Do you have a point of contact I could reach out to discuss collaboration further?

If you don't feel comfortable posting here you can reach me at DoYourReps@PianoGym.com

**Comment by rvilarl** [comment]
I updated my profile rvilarl@gmail.com
